# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/francesco/clion/clion-2017.2.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/francesco/clion/clion-2017.2.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francesco/CLionProject/Goku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francesco/CLionProject/Goku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/francesco/clion/clion-2017.2.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/francesco/clion/clion-2017.2.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francesco/CLionProject/Goku/CMakeFiles /home/francesco/CLionProject/Goku/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francesco/CLionProject/Goku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Goku

# Build rule for target.
Goku: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Goku
.PHONY : Goku

# fast build rule for target.
Goku/fast:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/build
.PHONY : Goku/fast

Animation.o: Animation.cpp.o

.PHONY : Animation.o

# target to build an object file
Animation.cpp.o:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Animation.cpp.o
.PHONY : Animation.cpp.o

Animation.i: Animation.cpp.i

.PHONY : Animation.i

# target to preprocess a source file
Animation.cpp.i:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Animation.cpp.i
.PHONY : Animation.cpp.i

Animation.s: Animation.cpp.s

.PHONY : Animation.s

# target to generate assembly for a file
Animation.cpp.s:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Animation.cpp.s
.PHONY : Animation.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Game.cpp.s
.PHONY : Game.cpp.s

Goku.o: Goku.cpp.o

.PHONY : Goku.o

# target to build an object file
Goku.cpp.o:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Goku.cpp.o
.PHONY : Goku.cpp.o

Goku.i: Goku.cpp.i

.PHONY : Goku.i

# target to preprocess a source file
Goku.cpp.i:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Goku.cpp.i
.PHONY : Goku.cpp.i

Goku.s: Goku.cpp.s

.PHONY : Goku.s

# target to generate assembly for a file
Goku.cpp.s:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Goku.cpp.s
.PHONY : Goku.cpp.s

Window.o: Window.cpp.o

.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/Window.cpp.s
.PHONY : Window.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Goku.dir/build.make CMakeFiles/Goku.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Goku"
	@echo "... Animation.o"
	@echo "... Animation.i"
	@echo "... Animation.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Goku.o"
	@echo "... Goku.i"
	@echo "... Goku.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

